#  This file should contain all the record creation needed to seed the database with its default
#  values.
#  The data can then be loaded with the rails db:seed command (or created alongside the database
#  with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# TODO remove non-kingdom cards
CARDS = [
  "Throne Room",
  "Alms",
  "Amulet",
  "Artificer",
  "Ball",
  "Bonfire",
  "Borrow",
  "Bridge Troll",
  "Caravan Guard",
  "Champion",
  "Coin of the Realm",
  "Disciple",
  "Distant Lands",
  "Dungeon",
  "Duplicate",
  "Expedition",
  "Ferry",
  "Fugitive",
  "Gear",
  "Giant",
  "Guide",
  "Haunted Woods",
  "Hero",
  "Hireling",
  "Inheritance",
  "Lost Arts",
  "Lost City",
  "Magpie",
  "Messenger",
  "Miser",
  "Mission",
  "Page",
  "Pathfinding",
  "Peasant",
  "Pilgrimage",
  "Plan",
  "Port",
  "Quest",
  "Raid",
  "Ranger",
  "Ratcatcher",
  "Raze",
  "Relic",
  "Royal Carriage",
  "Save",
  "Scouting Party",
  "Seaway",
  "Soldier",
  "Storyteller",
  "Swamp Hag",
  "Teacher",
  "Trade",
  "Training",
  "Transmogrify",
  "Travelling Fair",
  "Treasure Hunter",
  "Treasure Trove",
  "Warrior",
  "Wine Merchant",
  "Alchemist",
  "Apothecary",
  "Apprentice",
  "Familiar",
  "Golem",
  "Herbalist",
  "Philosopher's Stone",
  "Possession",
  "Scrying Pool",
  "Transmute",
  "University",
  "Vineyard",
  "Grey Mustang",
  "Rabbits",
  "Yard Dog",
  "Potion",
  "Copper",
  "Curse",
  "Duchy",
  "Estate",
  "Gold",
  "Province",
  "Silver",
  "Trash",
  "Colony",
  "Platinum",
  "Bag of Gold",
  "Diadem",
  "Fairgrounds",
  "Farming Village",
  "Followers",
  "Fortune Teller",
  "Hamlet",
  "Harvest",
  "Horn of Plenty",
  "Horse Traders",
  "Hunting Party",
  "Jester",
  "Menagerie",
  "Princess",
  "Remake",
  "Tournament",
  "Trusty Steed",
  "Young Witch",
  "Altar",
  "Armory",
  "Band of Misfits",
  "Bandit Camp",
  "Beggar",
  "Catacombs",
  "Count",
  "Counterfeit",
  "Cultist",
  "Death Cart",
  "Feodum",
  "Forager",
  "Fortress",
  "Graverobber",
  "Hermit",
  "Hovel",
  "Hunting Grounds",
  "Ironmonger",
  "Junk Dealer",
  "Knights",
  "Madman",
  "Marauder",
  "Market Square",
  "Mercenary",
  "Mystic",
  "Necropolis",
  "Overgrown Estate",
  "Pillage",
  "Poor House",
  "Procession",
  "Rats",
  "Rebuild",
  "Rogue",
  "Ruins",
  "Sage",
  "Scavenger",
  "Spoils",
  "Squire",
  "Storeroom",
  "Urchin",
  "Vagrant",
  "Wandering Minstrel",
  "Adventurer",
  "Chancellor",
  "Feast",
  "Spy",
  "Thief",
  "Woodcutter",
  "Bureaucrat",
  "Cellar",
  "Chapel",
  "Council Room",
  "Festival",
  "Gardens",
  "Laboratory",
  "Library",
  "Market",
  "Militia",
  "Mine",
  "Moat",
  "Moneylender",
  "Remodel",
  "Smithy",
  "Throne Room",
  "Village",
  "Witch",
  "Workshop",
  "Artisan",
  "Bandit",
  "Harbinger",
  "Merchant",
  "Poacher",
  "Sentry",
  "Vassal",
  "Advance",
  "Annex",
  "Aqueduct",
  "Archive",
  "Arena",
  "Bandit Fort",
  "Banquet",
  "Basilica",
  "Baths",
  "Battlefield",
  "Bustling Village",
  "Capital",
  "Castles",
  "Catapult",
  "Chariot Race",
  "Charm",
  "City Quarter",
  "Colonnade",
  "Conquest",
  "Crown",
  "Defiled Shrine",
  "Delve",
  "Dominate",
  "Donate",
  "Emporium",
  "Encampment",
  "Enchantress",
  "Engineer",
  "Farmers' Market",
  "Fortune",
  "Forum",
  "Fountain",
  "Gladiator",
  "Groundskeeper",
  "Keep",
  "Labyrinth",
  "Legionary",
  "Mountain Pass",
  "Museum",
  "Obelisk",
  "Orchard",
  "Overlord",
  "Palace",
  "Patrician",
  "Plunder",
  "Ritual",
  "Rocks",
  "Royal Blacksmith",
  "Sacrifice",
  "Salt the Earth",
  "Settlers",
  "Tax",
  "Temple",
  "Tomb",
  "Tower",
  "Triumph",
  "Triumphal Arch",
  "Villa",
  "Wall",
  "Wedding",
  "Wild Hunt",
  "Windfall",
  "Wolf Den",
  "Advisor",
  "Baker",
  "Butcher",
  "Candlestick Maker",
  "Doctor",
  "Herald",
  "Journeyman",
  "Masterpiece",
  "Merchant Guild",
  "Plaza",
  "Soothsayer",
  "Stonemason",
  "Taxman",
  "Border Village",
  "Cache",
  "Cartographer",
  "Crossroads",
  "Develop",
  "Duchess",
  "Embassy",
  "Farmland",
  "Fool's Gold",
  "Haggler",
  "Highway",
  "Ill-Gotten Gains",
  "Inn",
  "Jack of all Trades",
  "Mandarin",
  "Margrave",
  "Noble Brigand",
  "Nomad Camp",
  "Oasis",
  "Oracle",
  "Scheme",
  "Silk Road",
  "Spice Merchant",
  "Stables",
  "Trader",
  "Tunnel",
  "Coppersmith",
  "Great Hall",
  "Saboteur",
  "Scout",
  "Secret Chamber",
  "Tribute",
  "Baron",
  "Bridge",
  "Conspirator",
  "Courtyard",
  "Duke",
  "Harem",
  "Ironworks",
  "Masquerade",
  "Mining Village",
  "Minion",
  "Nobles",
  "Pawn",
  "Shanty Town",
  "Steward",
  "Swindler",
  "Torturer",
  "Trading Post",
  "Upgrade",
  "Wishing Well",
  "Courtier",
  "Diplomat",
  "Lurker",
  "Mill",
  "Patrol",
  "Replace",
  "Secret Passage",
  "Bad Omens",
  "Bard",
  "Bat",
  "Blessed Village",
  "Cemetery",
  "Changeling",
  "Cobbler",
  "Conclave",
  "Crypt",
  "Cursed Gold",
  "Cursed Village",
  "Delusion",
  "Den of Sin",
  "Devil's Workshop",
  "Druid",
  "Envious - Deluded",
  "Envy",
  "Exorcist",
  "Faithful Hound",
  "Famine",
  "Fear",
  "Fool",
  "Ghost",
  "Ghost Town",
  "Goat",
  "Greed",
  "Guardian",
  "Haunted Mirror",
  "Haunting",
  "Idol",
  "Imp",
  "Leprechaun",
  "Locusts",
  "Lost in the Woods",
  "Lucky Coin",
  "Magic Lamp",
  "Miserable - Twice Miserable",
  "Misery",
  "Monastery",
  "Necromancer",
  "Night Watchman",
  "Pasture",
  "Pixie",
  "Plague",
  "Pooka",
  "Pouch",
  "Poverty",
  "Raider",
  "Sacred Grove",
  "Secret Cave",
  "Shepherd",
  "Skulk",
  "The Earth's Gift",
  "The Field's Gift",
  "The Flame's Gift",
  "The Forest's Gift",
  "The Moon's Gift",
  "The Mountain's Gift",
  "The River's Gift.",
  "The Sea's Gift",
  "The Sky's Gift",
  "The Sun's Gift",
  "The Swamp's Gift",
  "The Wind's Gift",
  "Tormentor",
  "Tracker",
  "Tragic Hero",
  "Vampire",
  "War",
  "Werewolf",
  "Will-O'-Wisp",
  "Wish",
  "Zombie Apprentice",
  "Zombie Mason",
  "Zombie Spy",
  "Avanto",
  "Black Market",
  "Dismantle",
  "Envoy",
  "Governor",
  "Prince",
  "Sauna",
  "Stash",
  "Summon",
  "Walled Village",
  "Bank",
  "Bishop",
  "City",
  "Contraband",
  "Counting House",
  "Expand",
  "Forge",
  "Goons",
  "Grand Market",
  "Hoard",
  "King's Court",
  "Loan",
  "Mint",
  "Monument",
  "Mountebank",
  "Peddler",
  "Quarry",
  "Rabble",
  "Royal Seal",
  "Talisman",
  "Trade Route",
  "Vault",
  "Venture",
  "Watchtower",
  "Worker's Village",
  "Ambassador",
  "Bazaar",
  "Caravan",
  "Cutpurse",
  "Embargo",
  "Explorer",
  "Fishing Village",
  "Ghost Ship",
  "Haven",
  "Island",
  "Lighthouse",
  "Lookout",
  "Merchant Ship",
  "Native Village",
  "Navigator",
  "Outpost",
  "Pearl Diver",
  "Pirate Ship",
  "Salvager",
  "Sea Hag",
  "Smugglers",
  "Tactician",
  "Treasure Map",
  "Treasury",
  "Warehouse",
  "Wharf"
]

CARDS.each do |name|
  Card.create(name: name)
end

20.times do |i|
  k = Kingdom.create(name: "Kingdom #{i}")
  k.cards << Card.all.sample(10)
end
